version: '3'
services:
    apache:
        build: .docker/apache
        container_name: sf4_apache
        ports:
          - 80:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/var/www/sf4:delegated
          - /vendor:delegated
        depends_on:
          - php

    mysql:
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      container_name: sf4_mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: sf4
        MYSQL_USER: sf4
        MYSQL_PASSWORD: sf4

    phpmyadmin:
      image: phpmyadmin/phpmyadmin:latest
      container_name: sf4_phpmyadmin
      environment:
        MYSQL_USERNAME: sf4
        MYSQL_ROOT_PASSWORD: root
        PMA_HOST: mysql
      ports:
        - 8080:80
      links:
        - mysql

    php:
        build: .docker/php
        container_name: sf4_php
        volumes:
          - .:/var/www/sf4:delegated
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - mysql
        links:
          - mysql
